# Generated by Django 3.1.7 on 2021-08-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('cantidad', models.CharField(max_length=50)),
                ('precio', models.IntegerField(max_length=50)),
                ('ingredientes', models.CharField(max_length=50)),
            ],
        ),
    ]
