# Generated by Django 3.1.7 on 2021-08-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
