# Generated by Django 3.1.7 on 2021-08-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210818_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cantidad',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
