# Generated by Django 3.1.7 on 2021-08-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210818_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
