# Generated by Django 3.1.7 on 2021-08-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210818_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
