# Generated by Django 3.1.7 on 2021-08-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20210818_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
