# Generated by Django 3.1.7 on 2021-08-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('persona', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_pedido', models.CharField(max_length=50)),
                ('fecha_entrega', models.CharField(max_length=50)),
                ('IVA', models.CharField(max_length=50)),
                ('subtotal', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
                ('pago', models.CharField(max_length=10)),
                ('descuento', models.CharField(max_length=10)),
            ],
        ),
    ]
