# Generated by Django 3.1.7 on 2021-08-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('factura', models.CharField(max_length=50)),
                ('articulo', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=50)),
            ],
        ),
    ]
