# Generated by Django 3.1.7 on 2021-08-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='persona',
            new_name='cliente',
        ),
    ]
