# Generated by Django 3.1.7 on 2021-08-19 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20210817_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='estado',
        ),
    ]
